{
    "name": "Velux",
    "icon": "fas fa-house-user",
    "category": "automation",
    "version": "1.0.1",
    "author": "Psychokiller1888",
    "maintainers": [],
    "desc": "Control your velux equipment with your voice! this requires a velux remote hack",
    "aliceMinVersion": "1.0.0-b1",
    "systemRequirements": [""],
    "pipRequirements": [""],
    "conditions": {
        "lang": [
            "en"
        ]
    }
}
